FROM openjdk:8
RUN apt-get update
RUN apt-get -y install maven2
WORKDIR /root
CMD cd /root/KeyValueStore/Chord;mvn install -Dmaven.test.skip=true;cd /root/KeyValueStore/ObjectStore;mvn compile exec:java